<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */

$minicartShippingBlock = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('minicart-shipping-block')->toHtml();

?>

<div class="minicart-wrapper">
    <a class="action showcart dropdown-init" href="<?php /* @escapeNotVerified */ echo $block->getShoppingCartUrl(); ?>" data-bind="scope: 'minicart_content'">
        <span class="text material-icons">shopping_cart</span>
        <span class="counter qty empty" data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
            <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
        </span>
    </a>

    <div data-block="minicart" class="dropdown dropdown-slider-wrapper"></div>

    <?php if ($block->getIsNeedToDisplaySideBar()): ?>
        <div class="block block-minicart empty" data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".dropdown-init.showcart",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>

            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <?php echo $block->getChildHtml('minicart.addons'); ?>
            <div data-role="loader" class="loading-mask" style="display: none">
                <div class="loader">
                    <img src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>" alt="<?= /* @escapeNotVerified */ __('Loading...') ?>">
                </div>
            </div>
        </div>
    <?php endif ?>

    <script>
        window.checkout = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;
        window.checkout.moveToWishlist = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($this->getUrl('wishlist/index/add')) ?>;
        window.minicartShippingBlock = '<?php echo $minicartShippingBlock ?>';
    </script>

    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }
    </script>
</div>


