<?php

$helper = $this->helper('HelloBrave\CookieCompliance\Helper\Data');
if ($helper->getConfig('hellobrave_cookiecompliance/general/enabled')) {
    $message = $helper->getConfig('hellobrave_cookiecompliance/general/message');
    $link_separator = $helper->getConfig('hellobrave_cookiecompliance/general/link_separator');
    $learn_link = $helper->getConfig('hellobrave_cookiecompliance/general/learn_link');
    $learn_message = $helper->getConfig('hellobrave_cookiecompliance/general/learn_message');
    $hide_message = $helper->getConfig('hellobrave_cookiecompliance/general/hide_message');
    $custom_css = $helper->getConfig('hellobrave_cookiecompliance/general/custom_css'); ?>
    <div id="hb-cc-wrap" class="cookie-notice">
        <div class="cookie-notice-wrapper">
            <span class="info">
                <?php echo $message; ?>
            </span>

            <a class="button learn" href="<?php echo $learn_link; ?>" id="hb-cc-ll"><?php echo $learn_message; ?></a>

            <a class="button accept" href="#" id="hb-cc-hide"><?php echo $hide_message; ?></a>
        </div>
    </div>
    <script type="text/javascript">
        requirejs(['jquery','jquery.cookie'],function(jQuery){
            (function($) {
                // Show cookie bar
                if ($.cookie('cookie_notice') !== "true") {
                    $('.cookie-notice').slideDown();
                }
                // Handle hide button
                $('#hb-cc-hide').click(function(event) {
                    event.preventDefault();
                    $('.cookie-notice').slideUp();
                    // SET COOKIE
                    $.cookie('cookie_notice', "true", { expires: 28, path: '/' });
                })
            })(jQuery);
        });
    </script>
    <?php if (strlen($custom_css) > 0) { ?>
    <style type="text/css">
        <?php echo $custom_css; ?>
    </style>
    <?php } ?>
<?php

} ?>
