<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Pager template
 *
 * @see \Magento\Theme\Block\Html\Pager
 */
?>

<?php if ($block->getCollection()->getSize()): ?>

    <?php if ($block->getUseContainer()): ?>
    <div class="pager">
    <?php endif ?>

        <?php if ($block->getShowAmounts()): ?>
        <p class="toolbar-amount">
            <span class="toolbar-number">
            <?php if ($block->getLastPageNum()>1): ?>
                <?php /* @escapeNotVerified */ echo __('Items %1 to %2 of %3 total', $block->getFirstNum(), $block->getLastNum(), $block->getTotalNum()) ?>
            <?php elseif ($block->getTotalNum() == 1): ?>
                <?php /* @escapeNotVerified */ echo __('%1 Item', $block->getTotalNum()) ?>
            <?php else: ?>
                <?php /* @escapeNotVerified */ echo __('%1 Item(s)', $block->getTotalNum()) ?>
            <?php endif; ?>
            </span>
        </p>
        <?php endif ?>

        <?php if ($block->getLastPageNum()>1): ?>
        <div class="pages">
            <ul class="items pages-items" aria-labelledby="paging-label">

                <li class="item pages-item-first">
                    <?php if (!$block->isFirstPage()): ?>
                        <a class="first-page" href="<?php /* @escapeNotVerified */ echo $block->getPageUrl(1) ?>">
                            <i class="icon icon-chevron-left-double">
                                <?php /* @escapeNotVerified */ echo __('First page') ?>
                            </i>
                        </a>
                    <?php else: ?>
                        <span class="first-page" >
                            <i class="icon icon-chevron-left-double">
                                <?php /* @escapeNotVerified */ echo __('First page') ?>
                            </i>
                        </span>
                    <?php endif;?>
                </li>

                <li class="item pages-item-previous">
                    <?php $text = $block->getAnchorTextForPrevious() ? $block->getAnchorTextForPrevious() : '';?>

                    <?php if (!$block->isFirstPage()): ?>
                        <a class="<?php /* @escapeNotVerified */ echo $text ? 'link ' : 'action '?> previous" href="<?php /* @escapeNotVerified */ echo $block->getPreviousPageUrl() ?>" title="<?php /* @escapeNotVerified */ echo $text ? $text : __('Previous') ?>">
                            <span class="icon icon-chevron-left">
                                <?php /* @escapeNotVerified */ echo $text ? $text : __('Previous') ?>
                            </span>
                        </a>
                    <?php else: ?>
                        <span class="<?php /* @escapeNotVerified */ echo $text ? 'link ' : 'action '?> previous" >
                            <span class="icon icon-chevron-left">
                                <?php /* @escapeNotVerified */ echo $text ? $text : __('Previous') ?>
                            </span>
                        </span>
                    <?php endif;?>
                </li>


                <?php if ($block->canShowFirst()): ?>
                    <li class="item">
                        <a class="page first" href="<?php /* @escapeNotVerified */ echo $block->getFirstPageUrl() ?>">
                            <span>1</span>
                        </a>
                    </li>
                <?php endif;?>

                <?php if ($block->canShowPreviousJump()): ?>
                    <li class="item">
                        <a class="page previous jump" title="" href="<?php /* @escapeNotVerified */ echo $block->getPreviousJumpUrl() ?>">
                            <span>...</span>
                        </a>
                    </li>
                <?php endif;?>

                <?php foreach ($block->getFramePages() as $_page): ?>
                    <?php if ($block->isPageCurrent($_page)): ?>
                        <li class="item current">
                            <strong class="page">
                                <span><?php /* @escapeNotVerified */ echo $_page ?></span>
                            </strong>
                        </li>
                    <?php else: ?>
                        <li class="item">
                            <a href="<?php /* @escapeNotVerified */ echo $block->getPageUrl($_page) ?>" class="page">
                                <span><?php /* @escapeNotVerified */ echo $_page ?></span>
                            </a>
                        </li>
                    <?php endif;?>
                <?php endforeach;?>

                <?php if ($block->canShowNextJump()): ?>
                    <li class="item">
                        <a class="page next jump" title="" href="<?php /* @escapeNotVerified */ echo $block->getNextJumpUrl() ?>">
                            <span>...</span>
                        </a>
                    </li>
                <?php endif;?>

                <?php if ($block->canShowLast()): ?>
                  <li class="item">
                      <a class="page last" href="<?php /* @escapeNotVerified */ echo $block->getLastPageUrl() ?>">
                          <span class="label"><?php /* @escapeNotVerified */ echo __('Page') ?></span>
                          <span><?php /* @escapeNotVerified */ echo $block->getLastPageNum() ?></span>
                      </a>
                  </li>
                <?php endif;?>


                <li class="item pages-item-next">
                    <?php $text = $block->getAnchorTextForNext() ? $block->getAnchorTextForNext() : '';?>

                    <?php if (!$block->isLastPage()): ?>
                        <a class="<?php /* @escapeNotVerified */ echo $text ? 'link ' : 'action '?> next" href="<?php /* @escapeNotVerified */ echo $block->getNextPageUrl() ?>" title="<?php /* @escapeNotVerified */ echo $text ? $text : __('Next') ?>">
                            <i class="icon icon-chevron-right">
                                <?php /* @escapeNotVerified */ echo $text ? $text : __('Next') ?>
                            </i>
                        </a>
                    <?php else: ?>
                        <span class="<?php /* @escapeNotVerified */ echo $text ? 'link ' : 'action '?> next" >
                            <i class="icon icon-chevron-right">
                                <?php /* @escapeNotVerified */ echo $text ? $text : __('Next') ?>
                            </i>
                        </span>
                    <?php endif;?>
                </li>

                <li class="item pages-item-last">
                    <?php if (!$block->isLastPage()): ?>
                        <a class="last-page" href="<?php /* @escapeNotVerified */ echo $block->getPageUrl($block->getLastPageNum()) ?>">
                            <i class="icon icon-chevron-right-double">
                                <?php /* @escapeNotVerified */ echo __('Last page') ?>
                            </i>
                        </a>
                    <?php else: ?>
                        <span class="last-page" >
                            <i class="icon icon-chevron-right-double">
                                <?php /* @escapeNotVerified */ echo __('Last page') ?>
                            </i>
                        </span>
                    <?php endif;?>
                </li>

            </ul>
        </div>
        <?php endif; ?>

    <?php if ($block->isShowPerPage()): ?>
        <div class="limiter">
            <strong class="limiter-label"><?php /* @escapeNotVerified */ echo __('Show') ?></strong>
            <select id="limiter" data-mage-init='{"redirectUrl": {"event":"change"}}' class="limiter-options">
                <?php foreach ($block->getAvailableLimit() as $_key => $_limit): ?>
                    <option value="<?php /* @escapeNotVerified */ echo $block->getLimitUrl($_key) ?>"<?php if ($block->isLimitCurrent($_key)): ?>
                        selected="selected"<?php endif ?>>
                        <?php /* @escapeNotVerified */ echo $_limit ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
    <?php endif ?>

    <?php if ($block->getUseContainer()): ?>
    </div>
    <?php endif ?>

<?php endif ?>
