<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="checkout-adderess">
    <button>
        <i class="material-icons">help_outline</i>
    </button>
    <address>
        <strong><?= /* @escapeNotVerified */ __('Asistenza Cliente:'); ?></strong> 800 000 000 <br/>
        Lun-Ven. 09:00 - 18:00
    </address>
</div>
