<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\AuthorizationLink $block */

$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<li class="authorization-link <?php if($block->isLoggedIn()): ?>logged<?php else: ?>no-logged<?php endif; ?> link" data-label="<?= $block->escapeHtmlAttr(__('or')) ?>">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?><?= /* @noEscape */ $dataPostParam ?>>
        <i class="material-icons"><?php if($block->isLoggedIn()): ?>remove_circle<?php else: ?>account_circle<?php endif; ?></i>
        <span><?= $block->escapeHtml($block->getLabel()) ?></span>
    </a>
    <span class="no-link" <?= /* @noEscape */ $dataPostParam ?>>
        <i class="material-icons"><?php if($block->isLoggedIn()): ?>remove_circle<?php else: ?>account_circle<?php endif; ?></i>
        <span><?= $block->escapeHtml($block->getLabel()) ?></span>
    </span>
</li>
