<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\RegisterLink $block */

?>

<li class="register-link ">
    <a href="<?= /* @noEscape */ $block->getHref() ?>">
        <i class="material-icons">create</i>
        <span><?php echo __('Unisciti a noi') ?></span>
    </a>
</li>
