<?php $availableSocials = $block->getAvailableSocials(); ?>
<?php if ($block->canShow() && sizeof($availableSocials)): ?>
    <div class="block social-login-authentication-channel account-social-login">
        <div class="actions-toolbar">
            <?php foreach ($availableSocials as $key => $social): ?>
                <div class="social-btn social-btn-actions-toolbar <?= $key ?>-login">
                    <a class="btn btn-block btn-social btn-<?= $block->getBtnKey($key) ?>"
                       data-mage-init='{"socialProvider": {"url": "<?php echo $social['login_url'] ?>", "label": "<?php echo __('Login By %1', $social['label']) ?>"}}'>
                        <span class="fa fa-<?= $block->getBtnKey($key) ?>"></span>
                        <?php echo __('Sign in with') ?>
                        <?php echo $social['label'] ?>
                    </a>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>