<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
<?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;

    $macroCategory = $this->getData('isMacro') == "true" ? true : false;
?>
    <div class="block widget block-products-list <?= /* @noEscape */ $mode ?>">

        <?php if ($block->getTitle()): ?>
            <div class="block-title">
                <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
                <span>20 <?php echo __('products'); ?></span>
            </div>
        <?php endif ?>
        
        <div class="block-content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <ol class="product-items <?= /* @noEscape */ $type ?>" data-slick='{
                        "mobileFirst": true,
                        "centerMode": true,
                        "centerPadding": "30px",
                        "slidesToShow": 1,
                        "slidesToScroll": 1,
                        "infinite": true,
                        "responsive": [
                            {
                               "breakpoint": 480,
                               "settings": {
                                    "slidesToShow": 2
                                }
                            },
                            {
                                "breakpoint": 768,
                                "settings": "unslick"
                            }

                        ]
                    }'>
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php if ($iterator++ != 1): ?></li><?php endif ?>
                        <li class="product-item">
                            <div class="product-item-info <?php if($_item->getIsSalable()): ?>item-in-stock<?php else: ?>item-out-of-stock<?php endif; ?>">
                                <div class="product-img">
                                    <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                        <?php if (!$_item->getRequiredOptions()): ?>
                                            <div class="field choice related">
                                                <input type="checkbox" class="checkbox related" id="related-checkbox<?= /* @escapeNotVerified */ $_item->getId() ?>" name="related_products[]" value="<?= /* @escapeNotVerified */ $_item->getId() ?>" />
                                                <label class="label" for="related-checkbox<?= /* @escapeNotVerified */ $_item->getId() ?>"><span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span></label>
                                            </div>
                                        <?php endif; ?>
                                    <?php endif; ?>

                                    <?php if ($templateType): ?>
                                        <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>

                                    <?php if (!$_item->getIsSalable()): ?>
                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                    <?php endif; ?>

                                    <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                                        <?= $block->getImage($_item, $image)->toHtml() ?>
                                    </a>
                                </div>

                                <div class="product details product-item-details">

                                    <strong class="product name product-item-name"><a class="product-item-link" title="<?= $block->escapeHtml($_item->getName()) ?>" href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>">
                                            <?= $block->escapeHtml($_item->getName()) ?></a>
                                    </strong>

                                    <div class="price-box-list">
                                        <?php
                                            echo $block->getProductPriceHtml($_item, $type);
                                        ?>
                                    </div>

                                    <div class="product-item-inner">

                                        <?php
                                            $tierPrices = $_item->getTierPrices();
                                        ?>

                                        <?php if($tierPrices): ?>
                                            <div class="tier-prices-box">
                                                <ul class="prices-tier">
                                                    <?php foreach ($tierPrices as $index => $price): ?>

                                                        <?php if($index === 0): ?>
                                                            <li>
                                                                <?php
                                                                $qty = (int)$price['qty'];
                                                                $price = $price['value'];

                                                                $formattedPrice = $this->helper('Magento\Framework\Pricing\Helper\Data')->currency(number_format($price,2),true,false);

                                                                $priceTemplate = '<span class="price-container price-tier_price"><span class="price-wrapper"><span class="price">'.$formattedPrice.'</span></span></span>';

                                                                $savePercentageFormat = round(100 - ( (100 / $_item->getPrice()) * $price) );

                                                                echo __('Buy %1 for %2 each and <strong class="benefit">save<span class="percent tier-%3">&nbsp;%4</span></strong>',
                                                                    $qty, $priceTemplate, $index, $savePercentageFormat . '%'
                                                                )
                                                                ?>
                                                            </li>
                                                        <?php endif; ?>

                                                    <?php endforeach; ?>
                                                </ul>
                                            </div>
                                        <?php endif; ?>

                                    </div>
                                </div>
                                <div class="actions-buttons">
                                    <?php if ($showWishlist || $showCompare): ?>
                                        <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                <a href="#"
                                                   data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                    <i class="material-icons">favorite_border</i>
                                                </a>
                                            <?php endif; ?>
                                            <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                    <i class="material-icons">insert_chart_outlined</i>
                                                </a>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>

                                    <?php if ($showCart): ?>
                                        <div class="add-tocart">
                                            <div class="product actions product-item-actions">
                                                <?php if ($showCart): ?>
                                                    <div class="actions-primary">
                                                        <?php if ($_item->isSaleable()): ?>
                                                            <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                                <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?= /* @escapeNotVerified */ $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                                    <i class="material-icons">shopping_cart</i>
                                                                </button>
                                                            <?php else: ?>
                                                                <?php
                                                                $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                                $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                                ?>
                                                                <button class="action tocart primary" data-post='<?= /* @escapeNotVerified */ $postData ?>' type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                                    <i class="material-icons">shopping_cart</i>
                                                                </button>
                                                            <?php endif; ?>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>

                        <?= ($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>
            <?php if($macroCategory): ?>
                <p class="products-counter"><?php echo __('Articles displayed') ?> 4 <?php echo __('of') ?> 20</p>
                <div class="block-actions">
                    <div class="primary">
                        <a href="/" class="btn">
                            <?php echo __('Go to category') ?> <?php echo $block->escapeHtml(__($block->getTitle())) ?>
                        </a>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>
<?php endif;?>
