<?php
/**
 * Blackbird ContentManager Module
 *
 * NOTICE OF LICENSE
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@bird.eu so we can send you a copy immediately.
 *
 * @category        Blackbird
 * @package         Blackbird_ContentManager
 * @copyright       Copyright (c) 2018 Blackbird (https://black.bird.eu)
 * @author          Blackbird Team
 * @license         https://www.advancedcontentmanager.com/license/
 */
?>
<?php /** @var $block \Blackbird\ContentManager\Block\View\Field\Content */ ?>
<?php
$_identifier = $block->getIdentifier();
$_content = $block->getContent();

$_contentCollection = $block->getContentCollection(['*']);
?>
<?php if ($_contentCollection->count()) : ?>
    <ul class="ct-content-list" id="ct-content-list-<?= $block->getIdentifier(); ?>">
        <?php
        echo $block->getLayout()
            ->createBlock(\Blackbird\ContentManager\Block\Content\Widget\ContentList::class, '',
                ['data' => ['collection' => $_contentCollection]])
            ->toHtml();
        ?>
    </ul>
<?php endif; ?>
