<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>

<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>

    <div class="toolbar-first">
        <?php echo $block->getToolbarHtml() ?>
    </div>

    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info <?php if($_product->getIsSalable()): ?>item-in-stock<?php else: ?>item-out-of-stock<?php endif; ?>" data-container="product-grid">
                    <?php
                        $productImage = $block->getImage($_product, $image);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                    ?>

                    <div class="product-img">
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>

                        <?php if (!$_product->getIsSalable()): ?>
                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                        <?php endif; ?>

                        <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?php echo $productImage->toHtml(); ?>
                        </a>
                    </div>

                    <div class="product details product-item-details">

                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>

                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>

                        <div class="price-box-list">
                            <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                        </div>

                        <div class="product-item-inner">
                            <?php echo $block->getProductDetailsHtml($_product); ?>

                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                       class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>

                            <?php
                                $tierPrices = $_product->getTierPrices();
                            ?>

                            <?php if($tierPrices): ?>
                                <div class="tier-prices-box">
                                    <ul class="prices-tier">
                                        <?php foreach ($tierPrices as $index => $price): ?>

                                            <?php if($index === 0): ?>
                                                <li>
                                                    <?php
                                                    $qty = (int)$price['qty'];
                                                    $price = $price['value'];

                                                    $formattedPrice = $this->helper('Magento\Framework\Pricing\Helper\Data')->currency(number_format($price,2),true,false);

                                                    $priceTemplate = '<span class="price-container price-tier_price"><span class="price-wrapper"><span class="price">'.$formattedPrice.'</span></span></span>';

                                                    $savePercentageFormat = round(100 - ( (100 / $_product->getPrice()) * $price) );

                                                    echo __('Buy %1 for %2 each and <strong class="benefit">save<span class="percent tier-%3">&nbsp;%4</span></strong>',
                                                        $qty, $priceTemplate, $index, $savePercentageFormat . '%'
                                                    )
                                                    ?>
                                                </li>
                                            <?php endif; ?>

                                        <?php endforeach; ?>
                                    </ul>
                                </div>
                            <?php endif; ?>
                        </div>

                    </div>
                    <div class="actions-buttons">

                        <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                            <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                <?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                            <?php endif; ?>
                        </div>

                        <div class="add-tocart">
                            <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey')?>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary">
                                                <i class="material-icons">shopping_cart</i>
                                            </button>
                                        </form>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>


    <div class="toolbar-last">
        <button class="load-products"><?php echo __('Load more products'); ?></button>
        <?php echo $block->getToolbarHtml() ?>
    </div>


    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
