<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/** @var \Magento\ConfigurableProduct\Pricing\Render\FinalPriceBox$block */

/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;

$regularPriceValue = $priceModel->getAmount()->getValue();
$finalPriceValue = $finalPriceModel->getAmount()->getValue();
?>
<?php if (!$block->isProductList() && $block->hasSpecialPrice()): ?>
    <span class="old-price">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
	        'display_label'     => __('Regular Price'),
	        'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
	        'price_type'        => 'oldPrice',
	        'include_container' => true,
	        'skip_adjustments'  => true
        ]); ?>
    </span>

    <?php if(!$schema): ?>
        <?php echo '<span class="salebox-new">(-' . number_format((float)(1 - $finalPriceValue/$regularPriceValue) * 100, 0, '.', ''). '%)</span>'; ?>
    <?php endif; ?>

    <span class="special-price">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
            'display_label'     => __('Special Price'),
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]); ?>
    </span>

    <?php if($schema): ?>
        <?php echo '<span class="salebox-new">(-' . number_format((float)(1 - $finalPriceValue/$regularPriceValue) * 100, 0, '.', ''). '%)</span>'; ?>
    <?php endif; ?>

<?php else: ?>
    <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
        'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
        'price_type'        => 'finalPrice',
        'include_container' => true,
        'schema' => $schema
    ]); ?>
<?php endif; ?>

<?php if ($block->showMinimalPrice()): ?>
    <?php if ($block->getUseLinkForAsLowAs()):?>
        <a href="<?= /* @escapeNotVerified */ $block->getSaleableItem()->getProductUrl() ?>" class="minimal-price-link">
            <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>
        </a>
    <?php else:?>
        <span class="minimal-price-link">
            <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>
        </span>
    <?php endif?>
<?php endif; ?>
