<?php
/**
 * Blackbird MenuManager Module
 *
 * NOTICE OF LICENSE
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@bird.eu so we can send you a copy immediately.
 *
 * @category            Blackbird
 * @package		Blackbird_MenuManager
 * @copyright           Copyright (c) 2016 Blackbird (http://black.bird.eu)
 * @author		Blackbird Team
 */
?>
<?php
/** @var \Blackbird\MenuManager\Block\Menu $block */ ?>

<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded": true, "icons": {"submenu": false}, "position":false}}'>
        <?= /* @escapeNotVerified */ $block->getMenuHtml(); ?>
    </ul>
</nav>
