<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var $block \Magento\Checkout\Block\Cart */
?>
<?php if (!$block->hasError()): ?>
<?php $methods = $block->getMethods('methods') ?: $block->getMethods('top_methods') ?>
<ul class="checkout methods items checkout-methods-items">
<?php foreach ($methods as $method): ?>
    <?php if ($methodHtml = $block->getMethodHtml($method)): ?>
    <li class="item"><?= /* @escapeNotVerified */ $methodHtml ?></li>
    <?php endif; ?>
<?php endforeach; ?>
    <li class="item continue-shopping">
        <a class="button" href="/"><?php echo __('Continue shopping'); ?></a>
    </li>
</ul>
<?php endif; ?>
