<div class="admin__field field field-title" data-mage-init='{"menuManagerCustomField":{"type":"customfield"}}'>
    <label class="label admin__field-label" for="custom_field_id">URL Path</label>
    <div class="admin__field-control control">
        <input class="input-text admin__control-text" id="custom_field_id" type="text" data-mage-init='{"menuManagerEditorRename":{"type":"url_path"}}'/>
    </div>
</div>