<?php
/**
 * Blackbird ContentManager Module
 *
 * NOTICE OF LICENSE
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@bird.eu so we can send you a copy immediately.
 *
 * @category        Blackbird
 * @package         Blackbird_ContentManager
 * @copyright       Copyright (c) 2018 Blackbird (https://black.bird.eu)
 * @author          Blackbird Team
 * @license         https://www.advancedcontentmanager.com/license/
 */
?>
<?php /** @var $block \Blackbird\ContentManager\Block\Adminhtml\Content\Edit\Tab\Form\Type\File\Image */ ?>
<?php
$element = $block->getElement();
$note = $element->getNote() ? '<div class="note" id="'.$element->getId().'-note">'.$element->getNote().'</div>' : '';
$elementBeforeLabel = $element->getExtType() == 'checkbox admin__control-checkbox' || $element->getExtType() == 'radio admin__control-radio';
$fieldId = ($element->getHtmlContainerId()) ? ' id="'.$element->getHtmlContainerId().'"' : '';
$fieldClass = "admin__field field field-{$element->getId()} {$element->getCssClass()}";
$fieldClass .= ($elementBeforeLabel) ? ' choice' : '';
$fieldClass .= ($element->getRequired()) ? ' required _required' : '';
$fieldClass .= ($note) ? ' with-note' : '';
$fieldClass .= (!$element->getLabelHtml()) ? ' no-label' : '';

$fieldAttributes = $fieldId.' class="'.$fieldClass.'" '.$block->getUiId('form-field',
        $element->getId()).($element->getFieldExtraAttributes() ? ' '.$element->getFieldExtraAttributes() : '');

$imageField = $block->getCustomField();

$isRepeater = $element->getIsInRepeater(); // If image comes from repeater field
$identifierImageField = "content_image[".$imageField->getIdentifier()."]";
$dropzoneIdentifier = "dropzone_".$imageField->getIdentifier();

/*If image comes from a repeater field*/
if ($isRepeater) {
    $identifierImageField = $element->getIdentifierImageField();
    $dropzoneIdentifier = $element->getDropzoneName();
}


?>
<div<?= $fieldAttributes ?>>
    <?= $element->getLabelHtml() ?>
    <div class="admin__field-control control">
        <div class="field-file-image <?= $element->getName() ?>">
            <input type="hidden" class="img-data" name="<?= $element->getName() ?>" id="<?= $element->getName() ?>"
                   value="<?= $element->getEscapedValue() ?>"/>
            <input type="hidden" class="img-data-orig" name="<?= $element->getName() ?>_orig"
                   id="<?= $element->getName() ?>_orig" value="<?= $block->getOrigFileName() ?>"/>
            <div class="dropzone" id="<?= $dropzoneIdentifier ?>">
                <input type="file" name="<?= $identifierImageField ?>" <?= ($element->getRequired())
                    ? 'data-validate="{\'validate-required-image\':true}"' : '' ?> />
            </div>
        </div>
        <?= $note ?>
    </div>
</div>
<script>
    require([
        "jquery",
        'jquery/ui',
        'jquery/validate',
        'mage/translate',
        "Blackbird_ContentManager/js/html5imageupload"
    ], function ($) {

        var params = <?= $block->getJsonParams() ?>,
            elementName = "<?= $element->getName() ?>";

        //Remove square brackets in case the image field is a repeater
        elementName = elementName.replace(/[\[']+/g,'\\[').replace(/[\]']+/g,'\\]');

        params.onAfterCancel = function () {
            var imgDataInput = $(this.element).closest('.field-file-image').find('#' + elementName),
                imgDataOrigInput = $(this.element).closest('.field-file-image').find('#' + elementName +'_orig');

            if (imgDataInput) {
                imgDataInput.val('');
            }
            if (imgDataOrigInput) {
                imgDataOrigInput.val('');
            }
        };

        if (params.editcrop) {
            params.onAfterCancel = function () {
                var imgDataInput = $(this.element).closest('.field-file-image').find('#' + elementName),
                    imgDataOrigInput = $(this.element).closest('.field-file-image').find('#' + elementName +'_orig');

                if (imgDataInput) {
                    imgDataInput.val('');
                }
                if (imgDataOrigInput) {
                    imgDataOrigInput.val('');
                }
            };

            if (params.editcrop) {
                params.onAfterCancel = function () {
                    var imgDataInput = $(this.element).closest('.field-file-image').find('#' + elementName),
                        imgDataOrigInput = $(this.element).closest('.field-file-image').find('#' + elementName +'_orig');

                    if (imgDataInput) {
                        imgDataInput.val('');
                    }
                    if (imgDataOrigInput) {
                        imgDataOrigInput.val('');
                    }

                    this.options.buttonZoomout = true;
                    this.options.buttonZoomin = true;
                    this.options.buttonDone = true;
                    this.options.onAfterResetImage = function () {
                    };
                };
                params.onAfterResetImage = function () {
                    this.options.image = '<?= $block->getOrigImageUrl() ?>';
                    this.options.buttonZoomout = true;
                    this.options.buttonZoomin = true;
                    this.options.buttonDone = true;
                    this._init();
                };
            }
        }

        $('#<?= $dropzoneIdentifier ?>').html5imageupload(params);

        $.validator.addMethod(
            'validate-required-image', function (value, element) {
                var filled = false,
                    elemParent = $(element.closest('.field-file-image')),
                    imgData = elemParent.find('.img-data'),
                    imgDataOrig = elemParent.find('.img-data-orig'),
                    imgFinal = elemParent.find('.final');

                if (value || imgData.val() || imgDataOrig.val() || imgFinal.val()) {
                    filled = true;
                }

                return filled;
            },
            $.mage.__('This is a required field.')
        );
    });
</script>
